{
 "title": "Generic Node",
 "description": "Dashboard to get an overview of one Linux server.\r\n",
 "tags": [ "prometheus" ],
 "time": { "from": "now-30m", "to": "now-1m" },
 "templating": {
  "list": [
   { "name": "server", "query": "node_exporter:9100" }
  ]
 },
 "panels": [
  {
   "title": "Load",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "System load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$server\"}",
     "legendFormat": "load 1m"
    },
    {
     "expr": "node_load5{instance=~\"$server\"}",
     "legendFormat": "load 5m"
    },
    {
     "expr": "node_load15{instance=~\"$server\"}",
     "legendFormat": "load 15m"
    }
   ]
  },
  {
   "title": "Disk I/O per minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device=\"mmcblk0\", job=\"raspberry\"}[2m])",
     "legendFormat": "{{device}} bytes read"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{device=\"mmcblk0\", job=\"raspberry\"}[2m])",
     "legendFormat": "{{device}} bytes written"
    },
    {
     "expr": "rate(node_disk_io_time_weighted_seconds_total{device=\"mmcblk0\", job=\"raspberry\"}[2m])",
     "legendFormat": "{{device}} weighted time spent in IO, ms"
    }
   ]
  },
  {
   "title": "cpu busy %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "percent", "label": "cpu usage" }
   ],
   "targets": [
    {
     "expr": "100 - avg by (cpu) ( irate(node_cpu_seconds_total{mode=\"idle\",job=\"raspberry\"}[2m])) * 100",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Disk Space used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\", job=\"raspberry\"}"
    },
    {
     "expr": "node_filesystem_size_bytes{mountpoint=\"/\", job=\"raspberry\"} - node_filesystem_free_bytes{mountpoint=\"/\",job=\"raspberry\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Free memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$server\"} ",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$server\"}+node_memory_Buffers_bytes{instance=~\"$server\"}+node_memory_Cached_bytes  {instance=~\"$server\"}",
     "legendFormat": "MemFree"
    }
   ]
  },
  {
   "title": "Min Free disk space",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*min(node_filesystem_free{fstype !~ \"nfs|rpc_pipefs\",device!=\"/etc/auto.misc\",mountpoint !~ \"/boot|/net|/selinux\",instance=\"$server\"}/node_filesystem_size{fstype !~ \"nfs|rpc_pipefs\",device!=\"/etc/auto.misc\",mountpoint !~ \"/boot|/net|/selinux\",instance=\"$server\"})"
    }
   ]
  },
  {
   "title": "Free memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100*(node_memory_MemFree{instance=~\"$server\",job=\"raspberry\"}+node_memory_Buffers{instance=~\"$server\",job=\"raspberry\"}+node_memory_Cached{instance=~\"$server\",job=\"raspberry\"})/node_memory_MemTotal{instance=~\"$server\",job=\"raspberry\"}"
    }
   ]
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "IO Latency per device",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_ms{instance=~\"$server\"}[1m])/(irate(node_disk_reads_completed{instance=~\"$server\"}[1m])+irate(node_disk_writes_completed{instance=~\"$server\"}[1m]))",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Data transfer by NIC",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes{instance=~\"$server\",device!~\"lo\"}[5m])",
     "legendFormat": "received {{device}}"
    },
    {
     "expr": "irate(node_network_transmit_bytes{instance=~\"$server\",device!~\"lo\"}[5m])",
     "legendFormat": "transmitted  {{device}}"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "General Information",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "count(count(node_cpu{instance=\"$server\",job=\"raspberry\"}) without (mode)) without (cpu)",
     "legendFormat": "cpu_count"
    },
    {
     "expr": "node_memory_MemTotal{instance=\"$server\",job=\"raspberry\"}/1024/1024/1024",
     "legendFormat": "mem_total, GB"
    },
    {
     "expr": "(time()-node_boot_time{instance=\"$server\",job=\"raspberry\"})/3600/24",
     "legendFormat": "days_up"
    }
   ]
  },
  { "title": "Dashboard Row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } }
 ]
}