{
 "title": "Router",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Job",
    "query": {
     "query": "label_values(ifHCInOctets,  job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Router uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysUpTime{job=\"$Job\"} * 10"
    }
   ]
  },
  {
   "title": "Current download",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{job=\"router\", ifName=\"nas8\"}[1m]) * 8"
    }
   ]
  },
  {
   "title": "Current upload",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{job=\"router\", ifName=\"nas8\"}[1m]) * 8"
    }
   ]
  },
  {
   "title": "Line status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "group by (ifName) (ifOperStatus{ifName=\"nas8_1\"})"
    }
   ]
  },
  {
   "title": "bites per sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{job=\"router\", ifName=\"nas8\"}[1m]) * 8",
     "legendFormat": "rx"
    },
    {
     "expr": "irate(ifHCOutOctets{job=\"router\", ifName=\"nas8\"}[1m]) * -8",
     "legendFormat": "tx"
    }
   ]
  },
  { "title": "Packets/s tx/rx", "type": "timeseries", "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 } },
  { "title": "Line Rate?", "type": "timeseries", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 } },
  { "title": "Errors", "type": "timeseries", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 } }
 ]
}