global:
  scrape_interval: 30s
  scrape_timeout: 10s

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
  - job_name: raspberry
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'node_exporter:9100'
  - job_name: pihole
    metrics_path: /metrics
    static_configs:
      - targets:
          - '10.0.0.5:9617'
  - job_name: speedtest
    metrics_path: /metrics
    scrape_interval: 2h
    scrape_timeout: 30s
    static_configs:
      - targets:
          - '10.0.10.6:9112'
  - job_name: router
    metrics_path: /snmp
    static_configs:
      - targets:
        - 192.168.1.1  # SNMP device.
    params:
      module: [if_mib]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.0.10.5:9116  # The SNMP exporter's real hostname:port.
