global:
  scrape_interval: 60s
  scrape_timeout: 10s

scrape_configs:
  - job_name: prometheus
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
  - job_name: raspberry
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'node_exporter:9100'
